import './ExpenseForm.css'
import React, { useState } from 'react';

//THis module deals with user input

//input control
function ExpenseForm(props) {
    const [enteredTitle, setEnteredTitle] = useState('');
    const [enteredAmount, setEnteredAmount] = useState('');
    const [enteredDate, setEnteredDate] = useState('');

    //react reading title input
    function titleChangeHandler(event) {
        console.log(enteredTitle);
        setEnteredTitle(event.target.value);
        
    };

    //react read amount inpute
    function amountChangeHandler(event) {
        console.log(enteredAmount);
        setEnteredAmount(event.target.value);
        
    }

    //react read date inpute
    function dateChangeHandler(event) {
        console.log(enteredDate);
        setEnteredDate(event.target.value);
    }

    function submitHandler(event) {
        event.preventDefault();
        const expenseData = {
            title: enteredTitle,
            amount: enteredAmount,
            date: new Date(enteredDate)//this new date object is giving me time is giving me wrong time
        };

    props.onSaveExpenseData(expenseData);//passes data generated by submitHandler to NewExpenses.js to store into system
        setEnteredTitle('');
        setEnteredAmount('');
        setEnteredDate('');
    };

    return (
        <form onSubmit={submitHandler}>
            <div className='new-expense__controls'>
                <div className='new-expense__control'>
                    <label>Title</label>
                    <input type='text'value={enteredTitle} onChange={titleChangeHandler} />
                </div>
                <div className='new-expense__control'>
                    <label>Amount</label>
                    <input type='number' value={enteredAmount} min='0.01' step='0.01' onChange={amountChangeHandler} />
                </div>
                <div className='new-expense__control'>
                    <label>Date</label>
                    <input type='date' value={enteredDate} min='2019-01-01' max='2023-12-31' onChange={dateChangeHandler} />
                </div>
            </div>
            <div className='new-expense__actions'>
                <button type='button' onClick={props.onCancel}>Cancel</button>
                <button type='submit'>Add Expense</button>
            </div>
        </form>
    );
}

export default ExpenseForm; 